name: Python 2 Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3.10
    - name: Set up Python
      uses: actions/setup-python@v3.10
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run Python script
      run: python EB_av_v1.7_bet1a_.py
